# Sombras estilo CRT
shadow = false;
shadow-radius = 12;
shadow-opacity = 0.6;
shadow-offset-x = -7;
shadow-offset-y = -7;

# Shader verde monitor antigo (opcional)
glx-fshader-win = "
uniform float opacity;
void main() {
  gl_FragColor = vec4(0.4, 1.0, 0.4, opacity);
}
";

# Opacidade da barra do i3
opacity-rule = [
    "90:class_g = 'i3bar'"
];


vsync = true;
backend = "glx";
